/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.util.ArrayList;
import model.SAController;
import model.SAFactory;

/**
 *
 * @author mc
 */
public class MangeInstituteDashboard extends javax.swing.JFrame {
   
    AdminDashboard objMainUI;
SAController objController;
    /**
     * Creates new form AdminView
     */
    public MangeInstituteDashboard(AdminDashboard aThis) {
        
        
        initComponents();
        objMainUI = aThis;
        objController = SAFactory.getInstanceOfSMSController();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        RemoveBtn = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        logoffBtn = new javax.swing.JButton();
        showPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administration");
        setMinimumSize(new java.awt.Dimension(750, 600));
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Institute ");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 60);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        RemoveBtn.setBackground(new java.awt.Color(0, 153, 153));
        RemoveBtn.setText("Remove");
        jPanel1.add(RemoveBtn);
        RemoveBtn.setBounds(580, 40, 120, 30);

        SearchBtn.setBackground(new java.awt.Color(0, 153, 153));
        SearchBtn.setText("Search");
        jPanel1.add(SearchBtn);
        SearchBtn.setBounds(130, 40, 120, 30);

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setText("View");
        jPanel1.add(jButton3);
        jButton3.setBounds(280, 40, 120, 30);

        logoffBtn.setBackground(new java.awt.Color(0, 153, 153));
        logoffBtn.setText("Update");
        logoffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoffBtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoffBtn);
        logoffBtn.setBounds(430, 40, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 460, 810, 100);

        showPanel.setBackground(new java.awt.Color(0, 153, 153));

        Table.setBackground(new java.awt.Color(0, 153, 153));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "InstitueID", "InstitueName", "InstitueType", "OwnerName", "RegKey"
            }
        ));
        Table.setGridColor(new java.awt.Color(0, 153, 153));
        Table.setPreferredSize(new java.awt.Dimension(650, 120));
        Table.setSelectionBackground(new java.awt.Color(0, 153, 153));
        Table.setShowGrid(true);
        jScrollPane1.setViewportView(Table);

        showPanel.add(jScrollPane1);

        getContentPane().add(showPanel);
        showPanel.setBounds(0, 60, 810, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoffBtnActionPerformed
       
        this.setVisible(false);
        new HomeDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoffBtnActionPerformed

           private void loadData() {
               
        String searchKeyword = searchEmployee.getText();
        ArrayList<EmployeeDTO> empList = objController.viewEmployees(searchKeyword);
        PopulateDataFromDatabase(empList);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MangeInstituteDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MangeInstituteDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MangeInstituteDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MangeInstituteDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
        
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RemoveBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTable Table;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoffBtn;
    private javax.swing.JPanel showPanel;
    // End of variables declaration//GEN-END:variables
}
