/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import UI.admininterface.addinstitute;

/**
 *
 * @author mc
 */
public class OwnerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form OwnerDashboard
     */
    public OwnerDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        addInstiBtn = new javax.swing.JButton();
        ViewInstBtn = new javax.swing.JButton();
        AdrvtzBtn = new javax.swing.JButton();
        RmvBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        OwnerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 500, 600));
        setLocation(new java.awt.Point(210, 100));
        setMinimumSize(new java.awt.Dimension(780, 570));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("                                         Institue Name here");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 72);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(712, 62, 806, 10);

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        jPanel2.setAutoscrolls(true);
        jPanel2.setLayout(null);

        addInstiBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addInstiBtn.setText("Add Institue");
        addInstiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInstiBtnActionPerformed(evt);
            }
        });
        jPanel2.add(addInstiBtn);
        addInstiBtn.setBounds(0, 100, 130, 26);

        ViewInstBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewInstBtn.setText("View Institues");
        jPanel2.add(ViewInstBtn);
        ViewInstBtn.setBounds(0, 160, 130, 26);

        AdrvtzBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AdrvtzBtn.setText("Advertize");
        jPanel2.add(AdrvtzBtn);
        AdrvtzBtn.setBounds(0, 220, 130, 26);

        RmvBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RmvBtn.setText("Remove ");
        jPanel2.add(RmvBtn);
        RmvBtn.setBounds(0, 280, 130, 26);

        logOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logOutBtn.setText("Logout");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        jPanel2.add(logOutBtn);
        logOutBtn.setBounds(0, 340, 130, 26);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 130, 530);

        OwnerPanel.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout OwnerPanelLayout = new javax.swing.GroupLayout(OwnerPanel);
        OwnerPanel.setLayout(OwnerPanelLayout);
        OwnerPanelLayout.setHorizontalGroup(
            OwnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        OwnerPanelLayout.setVerticalGroup(
            OwnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(OwnerPanel);
        OwnerPanel.setBounds(130, 70, 680, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
       
        this.setVisible(false);
        new HomeDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void addInstiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInstiBtnActionPerformed
        this.setVisible(false);
        new addinstitute().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_addInstiBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OwnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OwnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OwnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OwnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OwnerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdrvtzBtn;
    private javax.swing.JPanel OwnerPanel;
    private javax.swing.JButton RmvBtn;
    private javax.swing.JButton ViewInstBtn;
    private javax.swing.JButton addInstiBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logOutBtn;
    // End of variables declaration//GEN-END:variables
}
